# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/im/msg/obj_msg/obj_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cai/pb/im/msg/obj_msg/obj_msg.proto',
  package='im.msg.obj_msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#cai/pb/im/msg/obj_msg/obj_msg.proto\x12\x0eim.msg.obj_msg\"N\n\x0eMsgContentInfo\x12\x15\n\rContentInfoId\x18\x01 \x01(\x0c\x12%\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x17.im.msg.obj_msg.MsgFile\"\x90\x01\n\x07MsgFile\x12\r\n\x05\x62usId\x18\x01 \x01(\r\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ileSize\x18\x03 \x01(\x04\x12\x10\n\x08\x66ileName\x18\x04 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64Time\x18\x05 \x01(\x03\x12\x10\n\x08\x66ileSha1\x18\x06 \x01(\x0c\x12\x0b\n\x03\x65xt\x18\x07 \x01(\x0c\x12\x0f\n\x07\x66ileMd5\x18\x08 \x01(\x0c\"I\n\x06MsgPic\x12\x13\n\x0bsmallPicUrl\x18\x01 \x01(\x0c\x12\x16\n\x0eoriginalPicUrl\x18\x02 \x01(\x0c\x12\x12\n\nlocalPicId\x18\x03 \x01(\r\"\xbb\x01\n\x06ObjMsg\x12\x0f\n\x07msgType\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x62stact\x18\x03 \x03(\x0c\x12\x10\n\x08titleExt\x18\x05 \x01(\x0c\x12#\n\x03pic\x18\x06 \x03(\x0b\x32\x16.im.msg.obj_msg.MsgPic\x12\x33\n\x0b\x63ontentInfo\x18\x07 \x03(\x0b\x32\x1e.im.msg.obj_msg.MsgContentInfo\x12\x14\n\x0creportIdShow\x18\x08 \x01(\r'
)




_MSGCONTENTINFO = _descriptor.Descriptor(
  name='MsgContentInfo',
  full_name='im.msg.obj_msg.MsgContentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ContentInfoId', full_name='im.msg.obj_msg.MsgContentInfo.ContentInfoId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='im.msg.obj_msg.MsgContentInfo.file', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=133,
)


_MSGFILE = _descriptor.Descriptor(
  name='MsgFile',
  full_name='im.msg.obj_msg.MsgFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='busId', full_name='im.msg.obj_msg.MsgFile.busId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filePath', full_name='im.msg.obj_msg.MsgFile.filePath', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileSize', full_name='im.msg.obj_msg.MsgFile.fileSize', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='im.msg.obj_msg.MsgFile.fileName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deadTime', full_name='im.msg.obj_msg.MsgFile.deadTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileSha1', full_name='im.msg.obj_msg.MsgFile.fileSha1', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ext', full_name='im.msg.obj_msg.MsgFile.ext', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileMd5', full_name='im.msg.obj_msg.MsgFile.fileMd5', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=280,
)


_MSGPIC = _descriptor.Descriptor(
  name='MsgPic',
  full_name='im.msg.obj_msg.MsgPic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='smallPicUrl', full_name='im.msg.obj_msg.MsgPic.smallPicUrl', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='originalPicUrl', full_name='im.msg.obj_msg.MsgPic.originalPicUrl', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localPicId', full_name='im.msg.obj_msg.MsgPic.localPicId', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=355,
)


_OBJMSG = _descriptor.Descriptor(
  name='ObjMsg',
  full_name='im.msg.obj_msg.ObjMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgType', full_name='im.msg.obj_msg.ObjMsg.msgType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='im.msg.obj_msg.ObjMsg.title', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abstact', full_name='im.msg.obj_msg.ObjMsg.abstact', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='titleExt', full_name='im.msg.obj_msg.ObjMsg.titleExt', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pic', full_name='im.msg.obj_msg.ObjMsg.pic', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentInfo', full_name='im.msg.obj_msg.ObjMsg.contentInfo', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reportIdShow', full_name='im.msg.obj_msg.ObjMsg.reportIdShow', index=6,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=545,
)

_MSGCONTENTINFO.fields_by_name['file'].message_type = _MSGFILE
_OBJMSG.fields_by_name['pic'].message_type = _MSGPIC
_OBJMSG.fields_by_name['contentInfo'].message_type = _MSGCONTENTINFO
DESCRIPTOR.message_types_by_name['MsgContentInfo'] = _MSGCONTENTINFO
DESCRIPTOR.message_types_by_name['MsgFile'] = _MSGFILE
DESCRIPTOR.message_types_by_name['MsgPic'] = _MSGPIC
DESCRIPTOR.message_types_by_name['ObjMsg'] = _OBJMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgContentInfo = _reflection.GeneratedProtocolMessageType('MsgContentInfo', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONTENTINFO,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgContentInfo)
  })
_sym_db.RegisterMessage(MsgContentInfo)

MsgFile = _reflection.GeneratedProtocolMessageType('MsgFile', (_message.Message,), {
  'DESCRIPTOR' : _MSGFILE,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgFile)
  })
_sym_db.RegisterMessage(MsgFile)

MsgPic = _reflection.GeneratedProtocolMessageType('MsgPic', (_message.Message,), {
  'DESCRIPTOR' : _MSGPIC,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgPic)
  })
_sym_db.RegisterMessage(MsgPic)

ObjMsg = _reflection.GeneratedProtocolMessageType('ObjMsg', (_message.Message,), {
  'DESCRIPTOR' : _OBJMSG,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.ObjMsg)
  })
_sym_db.RegisterMessage(ObjMsg)


# @@protoc_insertion_point(module_scope)
