# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/im/msg/obj_msg/obj_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cai/pb/im/msg/obj_msg/obj_msg.proto',
  package='im.msg.obj_msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#cai/pb/im/msg/obj_msg/obj_msg.proto\x12\x0eim.msg.obj_msg\"P\n\x0eMsgContentInfo\x12\x17\n\x0f\x63ontent_info_id\x18\x01 \x01(\x0c\x12%\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x17.im.msg.obj_msg.MsgFile\"\x97\x01\n\x07MsgFile\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\r\x12\x11\n\tfile_path\x18\x02 \x01(\x0c\x12\x11\n\tfile_size\x18\x03 \x01(\x04\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x11\n\tdead_time\x18\x05 \x01(\x03\x12\x11\n\tfile_sha1\x18\x06 \x01(\x0c\x12\x0b\n\x03\x65xt\x18\x07 \x01(\x0c\x12\x10\n\x08\x66ile_md5\x18\x08 \x01(\x0c\"O\n\x06MsgPic\x12\x15\n\rsmall_pic_url\x18\x01 \x01(\x0c\x12\x18\n\x10original_pic_url\x18\x02 \x01(\x0c\x12\x14\n\x0clocal_pic_id\x18\x03 \x01(\r\"\xc0\x01\n\x06ObjMsg\x12\x10\n\x08msg_type\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x62stact\x18\x03 \x03(\x0c\x12\x11\n\ttitle_ext\x18\x05 \x01(\x0c\x12#\n\x03pic\x18\x06 \x03(\x0b\x32\x16.im.msg.obj_msg.MsgPic\x12\x34\n\x0c\x63ontent_info\x18\x07 \x03(\x0b\x32\x1e.im.msg.obj_msg.MsgContentInfo\x12\x16\n\x0ereport_id_show\x18\x08 \x01(\r'
)




_MSGCONTENTINFO = _descriptor.Descriptor(
  name='MsgContentInfo',
  full_name='im.msg.obj_msg.MsgContentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_info_id', full_name='im.msg.obj_msg.MsgContentInfo.content_info_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='im.msg.obj_msg.MsgContentInfo.file', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=135,
)


_MSGFILE = _descriptor.Descriptor(
  name='MsgFile',
  full_name='im.msg.obj_msg.MsgFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bus_id', full_name='im.msg.obj_msg.MsgFile.bus_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='im.msg.obj_msg.MsgFile.file_path', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='im.msg.obj_msg.MsgFile.file_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='im.msg.obj_msg.MsgFile.file_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dead_time', full_name='im.msg.obj_msg.MsgFile.dead_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_sha1', full_name='im.msg.obj_msg.MsgFile.file_sha1', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ext', full_name='im.msg.obj_msg.MsgFile.ext', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_md5', full_name='im.msg.obj_msg.MsgFile.file_md5', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=289,
)


_MSGPIC = _descriptor.Descriptor(
  name='MsgPic',
  full_name='im.msg.obj_msg.MsgPic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='small_pic_url', full_name='im.msg.obj_msg.MsgPic.small_pic_url', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_pic_url', full_name='im.msg.obj_msg.MsgPic.original_pic_url', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_pic_id', full_name='im.msg.obj_msg.MsgPic.local_pic_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=370,
)


_OBJMSG = _descriptor.Descriptor(
  name='ObjMsg',
  full_name='im.msg.obj_msg.ObjMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='im.msg.obj_msg.ObjMsg.msg_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='im.msg.obj_msg.ObjMsg.title', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abstact', full_name='im.msg.obj_msg.ObjMsg.abstact', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_ext', full_name='im.msg.obj_msg.ObjMsg.title_ext', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pic', full_name='im.msg.obj_msg.ObjMsg.pic', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_info', full_name='im.msg.obj_msg.ObjMsg.content_info', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report_id_show', full_name='im.msg.obj_msg.ObjMsg.report_id_show', index=6,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=565,
)

_MSGCONTENTINFO.fields_by_name['file'].message_type = _MSGFILE
_OBJMSG.fields_by_name['pic'].message_type = _MSGPIC
_OBJMSG.fields_by_name['content_info'].message_type = _MSGCONTENTINFO
DESCRIPTOR.message_types_by_name['MsgContentInfo'] = _MSGCONTENTINFO
DESCRIPTOR.message_types_by_name['MsgFile'] = _MSGFILE
DESCRIPTOR.message_types_by_name['MsgPic'] = _MSGPIC
DESCRIPTOR.message_types_by_name['ObjMsg'] = _OBJMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgContentInfo = _reflection.GeneratedProtocolMessageType('MsgContentInfo', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONTENTINFO,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgContentInfo)
  })
_sym_db.RegisterMessage(MsgContentInfo)

MsgFile = _reflection.GeneratedProtocolMessageType('MsgFile', (_message.Message,), {
  'DESCRIPTOR' : _MSGFILE,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgFile)
  })
_sym_db.RegisterMessage(MsgFile)

MsgPic = _reflection.GeneratedProtocolMessageType('MsgPic', (_message.Message,), {
  'DESCRIPTOR' : _MSGPIC,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.MsgPic)
  })
_sym_db.RegisterMessage(MsgPic)

ObjMsg = _reflection.GeneratedProtocolMessageType('ObjMsg', (_message.Message,), {
  'DESCRIPTOR' : _OBJMSG,
  '__module__' : 'cai.pb.im.msg.obj_msg.obj_msg_pb2'
  # @@protoc_insertion_point(class_scope:im.msg.obj_msg.ObjMsg)
  })
_sym_db.RegisterMessage(ObjMsg)


# @@protoc_insertion_point(module_scope)
