"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class OidbSsoPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMAND_FIELD_NUMBER: builtins.int
    SERVICE_TYPE_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    CLIENT_VERSION_FIELD_NUMBER: builtins.int
    command: builtins.int
    service_type: builtins.int
    result: builtins.int
    body: builtins.bytes
    error_msg: typing.Text
    client_version: typing.Text
    def __init__(self,
        *,
        command: builtins.int = ...,
        service_type: builtins.int = ...,
        result: typing.Optional[builtins.int] = ...,
        body: builtins.bytes = ...,
        error_msg: typing.Optional[typing.Text] = ...,
        client_version: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error_msg",b"_error_msg","_result",b"_result","error_msg",b"error_msg","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error_msg",b"_error_msg","_result",b"_result","body",b"body","client_version",b"client_version","command",b"command","error_msg",b"error_msg","result",b"result","service_type",b"service_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error_msg",b"_error_msg"]) -> typing.Optional[typing_extensions.Literal["error_msg"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_result",b"_result"]) -> typing.Optional[typing_extensions.Literal["result"]]: ...
global___OidbSsoPacket = OidbSsoPacket

class DED3ReqBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TO_UIN_FIELD_NUMBER: builtins.int
    GROUP_CODE_FIELD_NUMBER: builtins.int
    MSG_SEQ_FIELD_NUMBER: builtins.int
    MSG_RAND_FIELD_NUMBER: builtins.int
    FROM_UIN_FIELD_NUMBER: builtins.int
    to_uin: builtins.int
    group_code: builtins.int
    msg_seq: builtins.int
    msg_rand: builtins.int
    from_uin: builtins.int
    def __init__(self,
        *,
        to_uin: builtins.int = ...,
        group_code: builtins.int = ...,
        msg_seq: builtins.int = ...,
        msg_rand: builtins.int = ...,
        from_uin: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["from_uin",b"from_uin","group_code",b"group_code","msg_rand",b"msg_rand","msg_seq",b"msg_seq","to_uin",b"to_uin"]) -> None: ...
global___DED3ReqBody = DED3ReqBody
