# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/msf/msg/onlinepush/onlinepush.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cai.pb.msf.msg.comm import comm_pb2 as cai_dot_pb_dot_msf_dot_msg_dot_comm_dot_comm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*cai/pb/msf/msg/onlinepush/onlinepush.proto\x12\x12msf.msg.onlinepush\x1a\x1e\x63\x61i/pb/msf/msg/comm/comm.proto\"\x89\x01\n\tPbPushMsg\x12\x1e\n\x03msg\x18\x01 \x01(\x0b\x32\x11.msf.msg.comm.Msg\x12\r\n\x05svrip\x18\x02 \x01(\x05\x12\x12\n\npush_token\x18\x03 \x01(\x0c\x12\x11\n\tping_flag\x18\x04 \x01(\r\x12\x14\n\x0cgeneral_flag\x18\t \x01(\r\x12\x10\n\x08\x62ind_uin\x18\n \x01(\x04')



_PBPUSHMSG = DESCRIPTOR.message_types_by_name['PbPushMsg']
PbPushMsg = _reflection.GeneratedProtocolMessageType('PbPushMsg', (_message.Message,), {
  'DESCRIPTOR' : _PBPUSHMSG,
  '__module__' : 'cai.pb.msf.msg.onlinepush.onlinepush_pb2'
  # @@protoc_insertion_point(class_scope:msf.msg.onlinepush.PbPushMsg)
  })
_sym_db.RegisterMessage(PbPushMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBPUSHMSG._serialized_start=99
  _PBPUSHMSG._serialized_end=236
# @@protoc_insertion_point(module_scope)
